---

- name: Add Harbor Helm repo
  ansible.builtin.command: helm repo add harbor https://helm.goharbor.io
  become: true

- name: Update Helm repos
  ansible.builtin.command: helm repo update

- name: Create values.yaml from template
  template:
    src: harbor-values.yml.j2
    dest: /tmp/harbor-values.yml

- name: Install Harbor Helm Chart
  ansible.builtin.command: helm upgrade --install harbor harbor/harbor -n tools -f /tmp/harbor-values.yml
